name: Android CI

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'latest'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache Android dependencies
        uses: actions/cache@v3
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        if: github.ref_name == 'main' || startsWith(github.ref_name, 'release/')
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > app/keystore.jks
          ./gradlew assembleRelease

      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7

      - name: Upload Release Artifacts
        if: github.ref_name == 'main' || startsWith(github.ref_name, 'release/')
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 30