name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        if: github.ref_name == 'master'
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease

      - name: Upload Debug Artifacts
        uses: softprops/action-gh-release@v2.0.8
        with:
          token: ${{ secrets.TOKEN }}
          files: app/build/outputs/apk/debug/*.apk
          retention-days: 7

      - name: Upload Release Artifacts
        if: github.ref_name == 'master'
        uses: softprops/action-gh-release@v2.0.8
        with:
          token: ${{ secrets.TOKEN }}
          files: app/build/outputs/apk/release/*.apk
          retention-days: 30